# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      backend:
        image: ghcr.io/a-poliakov/spring-pet-clinic:ci
        ports:
          - 9966:9966
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn -B install --file pom.xml -Djacoco.skip=true -DdisableXmlReport=true
#    - run: chmod +x mvnw
#    - run: apt install -y curl
#    - run: curl -I http://localhost:9966
#    - name: 'Maven build and test'
#      run: ./mvnw -B install --file pom.xml
